# Site settings
title: Oscar De Leon
description: Oscar's Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: OSCAR OF LION
user_description: El Salvadorian big boned mexican man that's ready to take your girl at any time that speaks 'spanish'
user_title: Computer scientist 
email: oscardeleonisagod@hotmail.com

instagram_username: oscar
facebook_username: oscar
linkedin_username: oscar
github_username:  oscar
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
